### ISSUE TITLE
Diffable Formatter Setting: Use self-closing tags

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tjw-lint/vue3-snapshot-serializer#12]
## Use self-closing tags

Would be false by default. Does not apply to void elements (`<input>`, `<img>`, etc.), use the `voidElements` setting for them.

```html
<!-- { useSelfClosing: false } -->
<div></div>
<span class="orange"></span>
<svg><path d=""></path></svg>
```
```html
<!-- { useSelfClosing: true } -->
<div />
<span class="orange" />
<svg><path d="" /></svg>
```

**Comment by TheJaredWilcurt** [comment]
Sure, I was trying to get the other PR's merged in before you started so you could avoid merge conflicts. But it looks like you pushed up a PR just as I was in the middle of merging and doing a release. So it goes.

**Comment by mauryapari** [comment]
Hey. No worries about the conflicts. I will have a look and resolve them.
